[2024-03-04T18:36:13.204+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Visualization_DAG.unzip_archive scheduled__2024-03-04T13:03:00+00:00 [queued]>
[2024-03-04T18:36:13.211+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Visualization_DAG.unzip_archive scheduled__2024-03-04T13:03:00+00:00 [queued]>
[2024-03-04T18:36:13.211+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-04T18:36:13.235+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): unzip_archive> on 2024-03-04 13:03:00+00:00
[2024-03-04T18:36:13.243+0530] {standard_task_runner.py:60} INFO - Started process 12405 to run task
[2024-03-04T18:36:13.247+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Visualization_DAG', 'unzip_archive', 'scheduled__2024-03-04T13:03:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/Analytics_data-checkpoint.py', '--cfg-path', '/tmp/tmp2_w0q1ex']
[2024-03-04T18:36:13.247+0530] {standard_task_runner.py:88} INFO - Job 213: Subtask unzip_archive
[2024-03-04T18:36:13.291+0530] {task_command.py:423} INFO - Running <TaskInstance: Visualization_DAG.unzip_archive scheduled__2024-03-04T13:03:00+00:00 [running]> on host arun-VM
[2024-03-04T18:36:13.349+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='Visualization_DAG' AIRFLOW_CTX_TASK_ID='unzip_archive' AIRFLOW_CTX_EXECUTION_DATE='2024-03-04T13:03:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-04T13:03:00+00:00'
[2024-03-04T18:36:13.350+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-04T18:36:13.351+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '!unzip -o /home/arun/airflow/dags/zipped_files/1902/1902_files.zip -d /home/arun/airflow/dags/unzipped_files']
[2024-03-04T18:36:13.362+0530] {subprocess.py:86} INFO - Output:
[2024-03-04T18:36:13.365+0530] {subprocess.py:93} INFO - /usr/bin/bash: line 1: !unzip: command not found
[2024-03-04T18:36:13.365+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-04T18:36:13.371+0530] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-04T18:36:13.373+0530] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Visualization_DAG, task_id=unzip_archive, execution_date=20240304T130300, start_date=20240304T130613, end_date=20240304T130613
[2024-03-04T18:36:13.392+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 213 for task unzip_archive (Bash command failed. The command returned a non-zero exit code 127.; 12405)
[2024-03-04T18:36:13.426+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-04T18:36:13.441+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
