[2024-03-04T18:34:39.857+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Visualization_DAG.unzip_archive scheduled__2024-03-04T12:54:00+00:00 [queued]>
[2024-03-04T18:34:39.863+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Visualization_DAG.unzip_archive scheduled__2024-03-04T12:54:00+00:00 [queued]>
[2024-03-04T18:34:39.863+0530] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-04T18:34:39.890+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): unzip_archive> on 2024-03-04 12:54:00+00:00
[2024-03-04T18:34:39.897+0530] {standard_task_runner.py:60} INFO - Started process 12293 to run task
[2024-03-04T18:34:39.901+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Visualization_DAG', 'unzip_archive', 'scheduled__2024-03-04T12:54:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/Analytics_data-checkpoint.py', '--cfg-path', '/tmp/tmp8olayh08']
[2024-03-04T18:34:39.902+0530] {standard_task_runner.py:88} INFO - Job 208: Subtask unzip_archive
[2024-03-04T18:34:39.951+0530] {task_command.py:423} INFO - Running <TaskInstance: Visualization_DAG.unzip_archive scheduled__2024-03-04T12:54:00+00:00 [running]> on host arun-VM
[2024-03-04T18:34:40.019+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='Visualization_DAG' AIRFLOW_CTX_TASK_ID='unzip_archive' AIRFLOW_CTX_EXECUTION_DATE='2024-03-04T12:54:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-04T12:54:00+00:00'
[2024-03-04T18:34:40.020+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-04T18:34:40.021+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '!unzip -o /home/arun/airflow/dags/zipped_files/1902/1902_files.zip -d /home/arun/airflow/dags/unzipped_files']
[2024-03-04T18:34:40.035+0530] {subprocess.py:86} INFO - Output:
[2024-03-04T18:34:40.038+0530] {subprocess.py:93} INFO - /usr/bin/bash: line 1: !unzip: command not found
[2024-03-04T18:34:40.038+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-04T18:34:40.044+0530] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/arun/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-04T18:34:40.046+0530] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Visualization_DAG, task_id=unzip_archive, execution_date=20240304T125400, start_date=20240304T130439, end_date=20240304T130440
[2024-03-04T18:34:40.067+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 208 for task unzip_archive (Bash command failed. The command returned a non-zero exit code 127.; 12293)
[2024-03-04T18:34:40.083+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-04T18:34:40.098+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
